### ISSUE TITLE
Doesn't works

### ISSUE THREAD

**Issue by lolsona** [q-zero/overpass-engine#1]
I get some erros when build project...

**Comment by Blcksky** [comment]
Can you post the error output?

**Comment by lolsona** [comment]
Ohh, I guess that It's not full project, Just a startup of it...
Also can you reupload HasakyEngine? I've been learning many things about networking from it, but one day it was gone, It was such a cool project & I really liked it... Thanks for that awesome one, I'll happy if see that again 👍

**Comment by Blcksky** [comment]
You can download the obsolete project from here: http://q-zr.de/hasaky-engine.zip

**Comment by lolsona** [comment]
Thanks for info... I would like to help you in development of it :)
When the compression will be completed in hasaky?

**Comment by Blcksky** [comment]
Sorry, but i want to keep development of the base on my side for now. Im not working on HasakyEngine anymore, but i'll implement similar compression on this one soon.

**Comment by lolsona** [comment]
I remember Overpass when was huge project like Hasaky where it is the complete one, that has High + Low level etc...? :)

**Comment by Blcksky** [comment]
Yes but it was basically just an extension of Hasaky just with other namespaces

**Comment by Blcksky** [comment]
This one will seperate more clearely between transport, message routing, handling and state synchronization.

**Comment by lolsona** [comment]
Awesome... I can't wait to see it dude :)

**Comment by lolsona** [comment]
Will it have a RPC methods?

**Comment by Blcksky** [comment]
Yes, but im also planning to use proxy classes for doing RPC calls without knowing, it's an RPC call.

**Comment by lolsona** [comment]
Ohh, Great :) can I add you in social networks such as Facebook or somewhere else mayby?

**Comment by lolsona** [comment]
Just a uestion, How does DataWriter works in your engine? I'm lil confused
