### ISSUE TITLE
DataCompression is not integrated.

### ISSUE THREAD

**Issue by MrKorra** [q-zero/overpass-engine#2]
Title is little bit strange, but I'm really confused about this:

Write((byte)DataCompressionType.None);

var compression = DataCompression.Compress(ref packet);

Write((byte)compression);

So, DataCompressionType is None, but I can't add new Compression type because that... Can you give me an example of compression? also void Decompress is so confusing, how it returns or etc...?

**Comment by Blcksky** [comment]
DataCompression.Compress is for compressing data automatically depending on its size and some other settings and returns the compression type (currently always None because its not implemented yet).

**Comment by MrKorra** [comment]
When will you start compression implementation?

**Comment by MaxPolster** [comment]
Im sorry, but compression has currently the lowest priority for me, because we have to get the high level api of the engine working as soon as possible.

**Comment by MaxPolster** [comment]
Moreover i think you were confused about how compression works, because the DataWriter writes "DataCompressionType.None" at some point. This is the point where the packet itself is "null" and null pointers are serialized too. So when deserializing, a null pointer turns out. So the compression is "None" because it makes no sense to compress a non existing packet.

**Comment by MrKorra** [comment]
So, remove compression then... at all

**Comment by MaxPolster** [comment]
?? We will need it later, so we have to build on the interface for providing future compatibility.

**Comment by MrKorra** [comment]
Long story short, I made "COMPRESSION" method of Overpass but... the problem is the ConnectionMessage... It's null somehow and can't be COMPRESSED or DECOMPRESSED, so I said if(packet != null) { COMPRESS} otherwise no else statement needed... so It only compresses if packet is existing value :) It worked good in my Scripts but after I integrated it to Overpass something went wrong...

Don't know what or how or why :/ Hope you can fix it soon 💯 I really like your style of Coding and methods & algorithms

**Comment by MrKorra** [comment]
Also then, I'm programmer too, and I want to be in q-zero team, I wish it and hope you can answer me about that ^_^ I really want to help in development and also I'll be great support for anyone :)

**Comment by MaxPolster** [comment]
What ConnectionMessage are you talking about? The initial exchange when connecting should not be compressed.

**Comment by MaxPolster** [comment]
I've invited you to the external development team, from that, you may contribute to all branches of this repo appart from the master branch.

**Comment by MrKorra** [comment]
The problem I see in Compression methods is that Compress uses DataCompressionType and Decompress uses void... 1) Can't use void if there is no variable upside that is ex:" public byte[] decompressedData; " and 2)Type on compression is absolute error, can't uses enum of byte to compress...

my tip is use bye[] Compress and byte[] Decompress they'll both do their job well... Just I've no idea how to put my compression lines in DataWriter & DataReader... I'll give you gist and try implement 

[https://gist.github.com/MrKorra/0e573b64752981fd26d31b09030c3c99](url)

**Comment by MaxPolster** [comment]
The thing is that the Compress method decides which algorithm to use and returns the algorithm type that was used. This type is also serialized and can be used to decompress the data.

**Comment by MaxPolster** [comment]
If you look at the compression class now, there is a threshold that is used to decide wether a packet gets compressed or not.

**Comment by MaxPolster** [comment]
https://github.com/q-zero/overpass-engine/blob/master/Project/Assets/Overpass/IO/DataCompression.cs#L66

Deflate compression is now implemented, but not tested and not integrated into the transport protocol.

**Comment by MaxPolster** [comment]
Data compression is now used in the high level api for rpc and state update buffers.
